language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  include:
    - php: 5.3
      env: 'COMPOSER_FLAGS="--prefer-lowest"'

before_script:
  - travis_retry composer install --no-interaction --prefer-dist
  - if [ "$COMPOSER_FLAGS" = "--prefer-lowest" ]; then composer update --prefer-lowest --with-dependencies phpunit/phpunit; fi;
  - vendor/bin/koharness

script:
  - cd /tmp/koharness && ./vendor/bin/phpunit --bootstrap=modules/unittest/bootstrap.php modules/unittest/tests.php

notifications:
  email: false
